services:
  trainer:
    build:
      context: .
      dockerfile: Dockerfile
    image: data-science-project-train
    volumes:
      - ./mlruns:/app/mlruns
      - ./mlflow.db:/app/mlflow.db

  mlflow-ui:
    image: data-science-project-train
    command:
      - mlflow
      - ui
      - --host
      - 0.0.0.0
      - --port
      - "5000"
      - --backend-store-uri
      - sqlite:///mlflow.db
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/app/mlruns
      - ./mlflow.db:/app/mlflow.db
